<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Report - Dark & Bright</title>
    <style>
        body {
            font-family: 'Inter', system-ui, -apple-system, sans-serif;
            font-size: 11px;
            color: #000;
            background: #fff;
            padding: 20px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f4f4f4;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 10px;
        }
        .header {
            margin-bottom: 30px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            border-bottom: 2px solid #000;
            padding-bottom: 20px;
        }
        .title {
            font-size: 24px;
            font-weight: 900;
            text-transform: uppercase;
        }
        .meta {
            text-align: right;
            font-size: 10px;
            text-transform: uppercase;
        }
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #000; color: #fff; border: none; cursor: pointer; text-transform: uppercase; font-weight: bold;">Print Report</button>
    </div>

    <div class="header">
        <div>
            <div class="title">Dark & Bright Studio</div>
            <div style="font-size: 10px; letter-spacing: 2px; margin-top: 5px;">Creative Defense Network — IDN</div>
        </div>
        <div class="meta">
            <div>Report Generated: {{ now()->format('d M Y, H:i') }}</div>
            <div>Total Records: {{ $orders->count() }}</div>
        </div>
    </div>

    <h3 style="text-transform: uppercase; margin-bottom: 10px;">Order Manifest</h3>

    <table>
        <thead>
            <tr>
                <th style="width: 50px;">ID</th>
                <th>Correspondent</th>
                <th>Service</th>
                <th>Payment</th>
                <th>Status</th>
                <th>Date</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $o)
            <tr>
                <td>#{{ $o->order_id }}</td>
                <td>
                    <div style="font-weight: bold;">{{ $o->customer_name ?? $o->name ?? ($o->user->name ?? 'Unknown') }}</div>
                    <div style="color: #666; font-size: 9px;">{{ $o->email }}</div>
                </td>
                <td>{{ ucwords(str_replace('-', ' ', $o->service)) }}</td>
                <td>
                   <span style="font-weight: bold; color: {{ ($o->payment_status == 'success') ? 'green' : (($o->payment_status == 'pending') ? 'orange' : 'red') }}">
                       {{ strtoupper($o->payment_status ?? 'PENDING') }}
                   </span>
                </td>
                <td>
                    <span style="font-weight: bold; color: {{ ($o->status == 'success') ? 'green' : (($o->status == 'pending') ? 'blue' : 'red') }}">
                        {{ strtoupper($o->status) }}
                    </span>
                </td>
                <td>{{ $o->created_at->format('d/m/Y') }}</td>
                <td style="text-align: right; font-family: monospace;">Rp{{ number_format($o->amount, 0, ',', '.') }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <th colspan="6" style="text-align: right;">TOTAL REVENUE</th>
                <th style="text-align: right;">Rp{{ number_format($orders->where('payment_status', 'success')->sum('amount'), 0, ',', '.') }}</th>
            </tr>
        </tfoot>
    </table>

    <div style="margin-top: 50px; font-size: 10px; color: #888; text-transform: uppercase; text-align: center;">
        End of Report -- System Generated by Dark & Bright Internal Protocol
    </div>
</body>
</html>
